### ISSUE TITLE
Tironian "et" being changed to numeral, 7

### ISSUE THREAD

**Issue by AdeDoyle** [takluyver/Unidecode#1]
Hi.

I've noticed that the Unicode character, "⁊", a Tironian note standing for Latin "et", is being changed to the numeral, "7". While they look alike, this doesn't seem like the best way to decode it, as it is never used to represent a numeral.

In Old Irish and Latin texts it was used as short-hand for the full word "et", so perhaps it should be replaced with "et". Alternatively, it is still used as an ampersand in modern Irish, so, maybe "&" would be a better replacement option?

Le meas,
Adrian.

**Comment by takluyver** [comment]
I think you want this repo: https://github.com/avian2/unidecode

I copied the repository onto Github about 10 years ago, but I haven't been involved with its development since then.

**Comment by AdeDoyle** [comment]
My mistake, sorry about that. Thanks for letting me know.
